### ISSUE TITLE
Question: Will this find .cmd binaries on Windows?

### ISSUE THREAD

**Issue by IanVS** [timoxley/npm-which#4]
I'm trying to figure out the best way of supporting Windows in a project I work on.  When a user on Windows does a global install, it seems that npm creates a `.cmd` executable. However, that does not seem to occur when it installs dependencies into `node_modules`.  Therefore, on Windows it seems to not be possible to spawn a binary of a module which my project depends on unless it is globally installed by the user.  

So, if I've explained the situation clearly enough, can you say if using `npm-which` (or perhaps `npm-run`) would solve the issues I'm facing?

**Comment by timoxley** [comment]
@IanVS `npm-which` uses the same algorithm that npm uses, so it *should* work if it works for npm, though I have not tested it

**Comment by timoxley** [comment]
If you find it does not work on windows please log a bug and I'll see what can be done.

**Comment by IanVS** [comment]
Yep, works as expected.  On windows, a `.CMD` file is created by `npm install` in the local `node_modules\.bin` directory.  Thanks, this is a big help!

**Comment by timoxley** [comment]
:hamburger: rad
