### ISSUE TITLE
Use in Cash

### ISSUE THREAD

**Issue by dthree** [timoxley/npm-which#5]
You think this is something we could use as a base for the `which` command in Cash? :)

https://github.com/dthree/cash

**Comment by timoxley** [comment]
I think so. What are the requirements?

**Comment by dthree** [comment]
Just the default functionality of the regular `which` command.

It's one of the most wanted commands per votes: https://github.com/dthree/cash/wiki/Roadmap

**Comment by timoxley** [comment]
@dthree it's a little different, as it will automatically include node_modules/.bin & friends in the PATH, but perhaps that's a nice perk for a js-centric CLI?

**Comment by timoxley** [comment]
@dthree actually, no this won't do. This is just about populating a PATH env var, it doesn't actually do any executable resolution.

**Comment by dthree** [comment]
Okay got it. Thanks for checking though!

**Comment by timoxley** [comment]
@dthree http://npm.im/which will do it

**Comment by dthree** [comment]
:+1:
